name: Gradle Check

on:
  push:
    branches-ignore:
    - develop

permissions: read-all

jobs:
  gradle-check:
    name: Gradle Check
    uses: interlok-tooling/reusable-workflows/.github/workflows/gradle-check.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

